2022-12-19 23:07:26,804 INFO    MainThread:161114 [wandb_setup.py:_flush():68] Configure stats pid to 161114
2022-12-19 23:07:26,804 INFO    MainThread:161114 [wandb_setup.py:_flush():68] Loading settings from /home/peppe/.config/wandb/settings
2022-12-19 23:07:26,804 INFO    MainThread:161114 [wandb_setup.py:_flush():68] Loading settings from /home/peppe/Desktop/Università/Projects/RL_Project-Generalising_game_environments_with_curiosity-driven_agents/wandb/settings
2022-12-19 23:07:26,804 INFO    MainThread:161114 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-19 23:07:26,804 INFO    MainThread:161114 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-19 23:07:26,804 INFO    MainThread:161114 [wandb_init.py:_log_setup():476] Logging user logs to /home/peppe/Desktop/Università/Projects/RL_Project-Generalising_game_environments_with_curiosity-driven_agents/wandb/run-20221219_230726-19vv040q/logs/debug.log
2022-12-19 23:07:26,804 INFO    MainThread:161114 [wandb_init.py:_log_setup():477] Logging internal logs to /home/peppe/Desktop/Università/Projects/RL_Project-Generalising_game_environments_with_curiosity-driven_agents/wandb/run-20221219_230726-19vv040q/logs/debug-internal.log
2022-12-19 23:07:26,804 INFO    MainThread:161114 [wandb_init.py:init():516] calling init triggers
2022-12-19 23:07:26,804 INFO    MainThread:161114 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'n_frames': 6, 'epochs': 10, 'batch_size': 64, 'rollout_steps': 256, 'episodes': 1000, 'actors': 8}
2022-12-19 23:07:26,804 INFO    MainThread:161114 [wandb_init.py:init():535] re-initializing run, found existing run on stack: 2w0a9c0x
2022-12-19 23:07:26,805 INFO    MainThread:161114 [wandb_run.py:_finish():1753] finishing run difra00/RL_Curiosity_agent/2w0a9c0x
2022-12-19 23:07:26,805 INFO    MainThread:161114 [jupyter.py:save_history():448] not saving jupyter history
2022-12-19 23:07:26,805 INFO    MainThread:161114 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2022-12-19 23:07:26,805 INFO    MainThread:161114 [wandb_init.py:_jupyter_teardown():408] cleaning up jupyter logic
2022-12-19 23:07:26,805 INFO    MainThread:161114 [wandb_run.py:_atexit_cleanup():1955] got exitcode: 0
2022-12-19 23:07:26,805 INFO    MainThread:161114 [wandb_run.py:_restore():1938] restore
2022-12-19 23:07:26,805 INFO    MainThread:161114 [wandb_run.py:_restore():1944] restore done
2022-12-19 23:07:32,596 INFO    MainThread:161114 [wandb_init.py:init():569] starting backend
2022-12-19 23:07:32,596 INFO    MainThread:161114 [wandb_init.py:init():573] setting up manager
2022-12-19 23:07:32,597 INFO    MainThread:161114 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-12-19 23:07:32,598 INFO    MainThread:161114 [wandb_init.py:init():580] backend started and connected
2022-12-19 23:07:32,605 INFO    MainThread:161114 [wandb_run.py:_label_probe_notebook():1116] probe notebook
2022-12-19 23:07:32,605 INFO    MainThread:161114 [wandb_run.py:_label_probe_notebook():1126] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-12-19 23:07:32,605 INFO    MainThread:161114 [wandb_init.py:init():658] updated telemetry
2022-12-19 23:07:32,609 INFO    MainThread:161114 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-19 23:07:45,545 WARNING MainThread:161114 [wandb_init.py:init():1099] interrupted
Traceback (most recent call last):
  File "/home/peppe/anaconda3/envs/my_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/peppe/anaconda3/envs/my_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/home/peppe/anaconda3/envs/my_env/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 261, in wait
    found = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/peppe/anaconda3/envs/my_env/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 118, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/peppe/anaconda3/envs/my_env/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 114, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/peppe/anaconda3/envs/my_env/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/peppe/anaconda3/envs/my_env/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
